{% set name = "catalystcoop.pudl_catalog" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/catalystcoop.pudl_catalog-{{ version }}.tar.gz
  sha256: ca26922e224896b9225e458d5ec68f8790989356cc37385c6144d68c3723c507

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - python >=3.8,<3.11
    - gcsfs >=2021.7,<2022.8.3
    - intake-parquet >=0.2.3,<0.3
    - intake-sqlite >=0.1.2
    - msgpack-python >=1,<2

test:
  imports:
    - pudl_catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/catalyst-cooperative/pudl-catalog
  summary: A catalog of open data related to the US energy system.
  doc_url: https://catalystcoop-pudl-catalog.readthedocs.io
  dev_url: https://github.com/catalyst-cooperative/pudl-catalog
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zaneselvans
